import styles from "./pagination.module.css";

export const Pagination = () => {
  return (
    <div className={styles.container}>
      <h1>pagination -- Pagination</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
