import styles from "./research-cta.module.css";

export const ResearchCta = () => {
  return (
    <div className={styles.container}>
      <h1>research-cta -- ResearchCta</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
