import styles from "./learning-levels.module.css";

export const LearningLevels = () => {
  return (
    <div className={styles.container}>
      <h1>learning-levels -- LearningLevels</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
