const PATHS_TO_TEST = [
  "/",
  "/about",
  "/about/staff",
  "/about/trustees",
  "/careers",
  "/stories",
  "/stories/jess",
  "/blog",
  "/blog/category/general",
  "/blog/covid-19-update-clients-at-the-centre-of-our-covid-19-strategy",
  "/blog/search?searchText=test",
  "/projects",
  "/projects/all",
  "/projects/search?searchText=test",
  "/projects/talking-mats-aac",
  "/resources",
  "/resources/all",
  "/resources/all?page=2",
  "/resources/abc-with-core-words",
  "/resources/a5-communication-book-direct-access",
  "/resources/look2talk",
  "/resources/you-matter",
  "/resources/gridwiz",
  "/404",
  "/contact",
  "/form/contact",
  "/learning",
  "/learning/communication-partners-i",
  "/learning/search",
  "/search?searchText=look2talk",
];

module.exports = PATHS_TO_TEST;
