###
### Everything below is taken from netlify docs and does not actually reflect our app.
### Its left here just for easy reference 
###

[[redirects]]
  from = "/trustees"
  to = "/about/trustees"
  status = 301

[[redirects]]
  from = "/account"
  to = "/my-acecentre"
  status = 301

[[redirects]]
  from = "/ace-centre-learning/my-courses"
  to = "/my-acecentre/courses"
  status = 301

[[redirects]]
  from = "/about/staff-member/*"
  to = "/about/staff/:splat"
  status = 301

[[redirects]]
  from = "/project/*"
  to = "/projects/:splat"
  status = 301

[[redirects]]
  from = "/news/*"
  to = "/blog/:splat"
  status = 301

[[redirects]]
  from = "/project/*"
  to = "/projects/:splat"
  status = 301

[[redirects]]
  from = "/news"
  to = "/blog"
  status = 301

[[redirects]]
  from = "/getting-started/faqs-frequently-asked-questions"
  to = "/getting-started"
  status = 301

[[redirects]]
  from = "/services/training"
  to = "/learning"
  status = 301

[[redirects]]
  from = "/services/information"
  to = "/services/advice-information"
  status = 301

[[redirects]]
  from = "/services/information/feedback/"
  to = "/form/information-appointment-feedback"
  status = 301

[[redirects]]
  from = "/privacy"
  to = "/page/privacy"
  status = 301

[[redirects]]
  from = "/ace-centre-privacy-policy-3"
  to = "/page/ace-centre-privacy-policy-3"
  status = 301

[[redirects]]
  from = "/purchase-terms-and-conditions"
  to = "/page/purchase-terms-and-conditions"
  status = 301

[[redirects]]
  from = "/safeguarding-policies"
  to = "/page/safeguarding-policies"
  status = 301

[[redirects]]
  from = "/wp-content/*"
  to = "https://backend.acecentre.org.uk/wp-content/:splat"
  status = 200

[[redirects]]
  from = "/ace-centre-learning"
  to = "/learning"
  status = 301

[[redirects]]
  from = "/resources/copyright-and-licence-terms-for-non-profit-items"
  to = "/page/copyright-and-licence-terms-for-non-profit-items"
  status = 301

[[redirects]]
  from = "/consent-form-2"
  to = "https://forms.office.com/Pages/ResponsePage.aspx?id=bFwgTJtTgU-Raj-O_eaPrEio9bWrHCRGoqxiKrWB3RlUMTJIR0NZVTNKMklEMjJHQ0dLQ1ZGMDBKTiQlQCN0PWcu"
  status = 301

[[redirects]]
  from = "/rehadapt-manuals"
  to = "https://acecentreuk.sharepoint.com/:f:/s/AnonymousShares/Ev7kOA08b1BFgY7tObc2XtgBzosxS_2fpYgOr1nnTJseVQ?e=BpZ91P"
  status = 307

[[redirects]]
  from = "/services/assessment"
  to = "/services/assessments"
  status = 301

[[redirects]]
  from = "/resources/electronic-text-based-comparison-chart"
  to = "https://backend.acecentre.org.uk/resources/electronic-text-based-comparison-chart"
  status = 301

[[redirects]]
  from = "/resources/electronic-text-based-features-checklist"
  to = "https://backend.acecentre.org.uk/resources/electronic-text-based-features-checklist"
  status = 301

[[redirects]]
  from = "/resources/developing-using-communication-book-templates"
  to = "/resources/developing-using-communication-book"
  status = 301

[[redirects]]
  from = "/services/assessment/nhs-referral"
  to = "/services/nhs/assessments"
  status = 301

[[redirects]]
  from = "/resources/access-to-low-tech-symbol-based-resources-when-pointing-is-difficult"
  to = "/resources/paper-based-resources-to-support-communication-for-adults-with-progressive-conditions"
  status = 301

[[redirects]]
  from = "/resources/using-low-tech-symbol-based-systems-with-children"
  to = "/resources/access-to-paper-based-symbol-resources-when-pointing-is-difficult"
  status = 301

[[redirects]]
  from = "/resources/getting-started-aac"
  to = "/resources/all?category=made-by-ace&subcategory=e-books"
  status = 301

[[redirects]]
  from = "/ducbdownloads"
  to = "/resources/developing-using-communication-book"
  status = 301

[[redirects]]
  from = "/youmatter"
  to = "/resources/all?category=shop&searchText=youmatter&page=1"
  status = 301

[[redirects]]
  from = "/learning/learn-at-engineering"
  to = "/learning/cad-in-at"
  status = 301

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/netlify-plugins/sitemap"

[[plugins]]
  package = "/netlify-plugins/expose-env-variables"

[[plugins]]
  package = "/netlify-plugins/output-config"

[[plugins]]
  package = "/netlify-plugins/copy-redirects"

[build]
  command = "yarn build && yarn build-function"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  # base = "project/"

  # Directory that contains the deploy-ready HTML files and assets generated by
  # the build. This is relative to the base directory if one has been set, or the
  # root directory if a base has not been set. This sample publishes the
  # directory located at the absolute path "root/project/build-output"
  # publish = "build-output/"

  # Default build command.

  # Directory with the serverless functions, including background functions,
  # to deploy to AWS. This is relative to the base directory if one has been set, 
  # or the root directory if a base has not been set.
  # functions = "functions/"

# Production context: all deploys from the Production branch set in your site’s
# deploy contexts will inherit these settings.
# [context.production]
#   publish = "output/"
#   command = "make publish"
#   environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }

# Deploy Preview context: all deploys generated from a pull/merge request will
# inherit these settings.
# [context.deploy-preview]
#   publish = "dist/"

# Here is another way to define context specific environment variables.
# [context.deploy-preview.environment]
#   ACCESS_TOKEN = "not so secret"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
# [context.branch-deploy]
#   command = "echo branch"
# [context.branch-deploy.environment]
#   NODE_ENV = "development"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
# [context.staging] # “staging” is a branch name
#   command = "echo 'staging'"
#   base = "staging"

# For contexts of branches with special characters, enclose the branch name
# with quotes.
# [context."feat/branch"]
#   command = "echo 'special branch'"
#   base = "branch"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

# A basic redirect rule
# [[redirects]]
#   from = "/*"
#   to = "/blog/:splat"

# A redirect rule with many of the supported properties
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"

#   # The default HTTP status code is 301, but you can define a different one.
#   status = 302

#   # By default, redirects won’t be applied if there’s a file with the same
#   # path as the one defined in the `from` property. Setting `force` to `true`
#   # will make the redirect rule take precedence over any existing files.
#   force = true

#   # Redirect from /old-path?id=123 to /new-path. Each combination of query
#   # params needs to be defined in a separate [[redirects]] block.
#   # More information at https://docs.netlify.com/routing/redirects/redirect-options/#query-parameters
#   query = {id = ":id"}

#   # Redirect based on browser language and geolocation.
#   conditions = {Language = ["en"], Country = ["US"]}

#   # Sign each request with a value defined in an environment variable
#   signed = "API_SIGNATURE_TOKEN"

#   # You can also define custom headers within your redirects blocks.
#   [redirects.headers]
#     X-From = "Netlify"
#     X-Api-Key = "some-api-key-string"

# Role-based redirects do not have a “to” property.
# [[redirects]]
#   from = "/gated-path"
#   status = 200
#   conditions = {Role = ["admin"]}
#   force = true

# The following redirect is intended for use with most SPAs that handle
# routing internally.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     Content-Security-Policy = "frame-ancestors https://www.facebook.com"

#     # Multi-value headers are expressed with multi-line strings.
# 	cache-control = '''
# 	max-age=0,
# 	no-cache,
# 	no-store,
# 	must-revalidate'''

#     # Basic-Auth allows you to password protect your whole site.
#     # This feature may not be available on all plans.
#     Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"