import styles from "./blog-search.module.css";

export const BlogSearch = () => {
  return (
    <div className={styles.container}>
      <h1>blog-search -- BlogSearch</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
