import styles from "./working-at-ace.module.css";

export const WorkingAtAce = () => {
  return (
    <div className={styles.container}>
      <h1>working-at-ace -- WorkingAtAce</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
