import styles from "./coupon-area.module.css";

export const CouponArea = () => {
  return (
    <div className={styles.container}>
      <h1>coupon-area -- CouponArea</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
