import styles from "./address-field.module.css";

export const AddressField = () => {
  return (
    <div className={styles.container}>
      <h1>address-field -- AddressField</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};

export const BillingDetails = () => {
  return <AddressField />;
};

export const ShippingDetails = () => {
  return <AddressField />;
};
