import styles from "./dashboard-card.module.css";

export const DashboardCard = () => {
  return (
    <div className={styles.card}>
      <h1>dashboard-card -- DashboardCard</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
