import styles from "./our-vision.module.css";

export const OurVision = () => {
  return (
    <div className={styles.container}>
      <h1>our-vision -- OurVision</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
