import styles from "./table.module.css";

export const Table = () => {
  return (
    <div className={styles.container}>
      <h1>table -- Table</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
