import styles from "./product-filters.module.css";
import { ComboBox, Item } from "@react-spectrum/combobox";
import { useState } from "react";

export const ProductFilters = ({ categories }) => {
  let options = [
    { id: 1, name: "Aerospace" },
    { id: 2, name: "Mechanical" },
    { id: 3, name: "Civil" },
    { id: 4, name: "Biomedical" },
    { id: 5, name: "Nuclear" },
    { id: 6, name: "Industrial" },
    { id: 7, name: "Chemical" },
    { id: 8, name: "Agricultural" },
    { id: 9, name: "Electrical" },
  ];
  let [majorId, setMajorId] = useState();

  return (
    <div className={styles.container}>
      <ComboBox
        label="Pick a engineering major"
        defaultItems={options}
        onSelectionChange={setMajorId}
      >
        {(item) => <Item>{item.name}</Item>}
      </ComboBox>
      <h1>product-filters -- ProductFilters</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
