import styles from "./product-filters.module.css";

export const ProductFilters = () => {
  return (
    <div className={styles.container}>
      <h1>product-filters -- ProductFilters</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
