import styles from "./filter-people.module.css";

export const FilterPeople = () => {
  return (
    <div className={styles.container}>
      <h1>filter-people -- FilterPeople</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
