import styles from "./people-list.module.css";

export const PeopleList = () => {
  return (
    <div className={styles.container}>
      <h1>people-list -- PeopleList</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
