import styles from "./OurVision.module.css";

export const Ourvision = () => {
  return (
    <div className={styles.container}>
      <h1>OurVision -- Ourvision</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
