import styles from "./words-from.module.css";

export const WordsFrom = () => {
  return (
    <div className={styles.container}>
      <h1>words-from -- WordsFrom</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
