import styles from "./resources-share.module.css";

export const ResourcesShare = () => {
  return (
    <div className={styles.container}>
      <h1>resources-share -- ResourcesShare</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
