import styles from "./all-stories.module.css";

export const AllStories = () => {
  return (
    <div className={styles.container}>
      <h1>all-stories -- AllStories</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
