import styles from "./details-form.module.css";

export const DetailsForm = () => {
  return (
    <div className={styles.container}>
      <h1>details-form -- DetailsForm</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
