import styles from "./careers-at-ace.module.css";

export const CareersAtAce = () => {
  return (
    <div className={styles.container}>
      <h1>careers-at-ace -- CareersAtAce</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
