import styles from "./resources-image.module.css";

export const ResourcesImage = () => {
  return (
    <div className={styles.container}>
      <h1>resources-image -- ResourcesImage</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
