name: "Setup the env"
description: "Install node, install NPM deps, setup cache, patch and unpatch deps"
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - uses: actions/cache@v2
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

    - name: Install NPM deps
      run: yarn install

    - name: Patch deps
      run: yarn patch
