import styles from "./trustee-list.module.css";

export const TrusteeList = () => {
  return (
    <div className={styles.container}>
      <h1>trustee-list -- TrusteeList</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
