import styles from "./contact-cards.module.css";

export const ContactCards = () => {
  return (
    <div className={styles.container}>
      <h1>contact-cards -- ContactCards</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
