import styles from "./staff-list.module.css";

export const StaffList = () => {
  return (
    <div className={styles.container}>
      <h1>staff-list -- StaffList</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
