import styles from "./video-popover.module.css";

export const VideoPopover = () => {
  return (
    <div className={styles.container}>
      <h1>video-popover -- VideoPopover</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
