import styles from "./our-funding.module.css";

export const OurFunding = () => {
  return (
    <div className={styles.container}>
      <h1>our-funding -- OurFunding</h1>
      <p>This component is generated by plop</p>
    </div>
  );
};
