name: Cypress integration
on: [workflow_dispatch]

jobs:
  CypressIntegration:
    runs-on: ubuntu-latest
    env:
      CYPRESS_INCLUDE_TAGS: pre-deploy
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: npm i --force cypress @testing-library/cypress cypress-tags typescript

      - name: Cypress run
        with:
          config: baseUrl=https://integration--acecentreorguk.netlify.app
          record: true
          install: false
          parallel: true
          group: Github actions
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: cypress-io/github-action@v2
