name: Reusable Cypress Job
on:
  workflow_call:
    inputs:
      baseUrl:
        required: true
        type: string
    secrets:
      CYPRESS_MOODLE_USERNAME:
        required: true
      CYPRESS_MOODLE_PASSWORD:
        required: true
      CYPRESS_SECRET:
        required: true
      WORDPRESS_AUTH:
        required: true
      CYPRESS_MOODLE_AUTH:
        required: true

jobs:
  RunTests:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate UUID
        id: generate-uuid
        run: echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT

      - name: Cypress run
        with:
          config: baseUrl=${{ inputs.baseUrl }},retries=0
          record: true
          install: true
          parallel: false
          browser: chrome
          ci-build-id: ${{ steps.generate-uuid.outputs.uuid }}
        env:
          CYPRESS_MOODLE_USERNAME: ${{ secrets.CYPRESS_MOODLE_USERNAME }}
          CYPRESS_MOODLE_PASSWORD: ${{ secrets.CYPRESS_MOODLE_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_WORDPRESS_AUTH: ${{ secrets.WORDPRESS_AUTH }}
          CYPRESS_MOODLE_AUTH: ${{ secrets.CYPRESS_MOODLE_AUTH }}
        uses: cypress-io/github-action@v6
