name: Cypress Gauntlet
on: [workflow_dispatch]

jobs:
  GauntletRunOnePost:
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: post-deploy
      baseUrl: https://acecentre.org.uk

  GauntletRunTwoPost:
    needs: [GauntletRunOnePost]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: post-deploy
      baseUrl: https://acecentre.org.uk

  GauntletRunThreePost:
    needs: [GauntletRunTwoPost]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: post-deploy
      baseUrl: https://acecentre.org.uk

  GauntletRunFourPost:
    needs: [GauntletRunThreePost]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: post-deploy
      baseUrl: https://acecentre.org.uk

  GauntletRunFivePost:
    needs: [GauntletRunFourPost]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: post-deploy
      baseUrl: https://acecentre.org.uk

  GauntletRunOnePre:
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: pre-deploy
      baseUrl: https://live-acecentregrouk-z9iru.ondigitalocean.app

  GauntletRunTwoPre:
    needs: [GauntletRunOnePre]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: pre-deploy
      baseUrl: https://live-acecentregrouk-z9iru.ondigitalocean.app

  GauntletRunThreePre:
    needs: [GauntletRunTwoPre]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: pre-deploy
      baseUrl: https://live-acecentregrouk-z9iru.ondigitalocean.app

  GauntletRunFourPre:
    needs: [GauntletRunThreePre]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: pre-deploy
      baseUrl: https://live-acecentregrouk-z9iru.ondigitalocean.app

  GauntletRunFivePre:
    needs: [GauntletRunFourPre]
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
    with:
      tags: pre-deploy
      baseUrl: https://live-acecentregrouk-z9iru.ondigitalocean.app
