name: Cypress
on: [pull_request]
jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Netlify
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Waiting for Netlify Preview
        uses: josephduffy/wait-for-netlify-action@v1
        id: wait-for-netlify-preview
        with:
          site_name: "acecentreorguk"
          max_timeout: 60

      - name: output url
        run: echo "${{ steps.wait-for-netlify-preview.outputs.url }}"

      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install NPM deps
        run: yarn install

      - name: Run Cypress
        run: yarn cypress:run

      - uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: artifacts
          # Github has size limits so this avoids hitting them
          retention-days: 1
