name: Cypress integration
on: [workflow_dispatch]

jobs:
  CypressPostDeploy:
    runs-on: ubuntu-latest
    env:
      CYPRESS_INCLUDE_TAGS: post-deploy
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: npm i --force cypress @testing-library/cypress cypress-tags typescript

      - name: Cypress run
        with:
          config: baseUrl=https://acecentre.org.uk
          record: true
          install: false
        env:
          CYPRESS_MOODLE_USERNAME: ${{ secrets.CYPRESS_MOODLE_USERNAME }}
          CYPRESS_MOODLE_PASSWORD: ${{ secrets.CYPRESS_MOODLE_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_WORDPRESS_AUTH: ${{ secrets.WORDPRESS_AUTH }}
        uses: cypress-io/github-action@v4.1.0
