name: Deploy Production
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Everyday at 2AM
    - cron: "0 2 * * *"

jobs:
  GetUniqueBuildId:
    runs-on: ubuntu-latest
    outputs:
      buildId: ${{ steps.time.outputs.dateTime }}
    steps:
      - name: Get Time
        id: time
        uses: Plabick/Remote-Time-Action@V1.0
        with:
          timezone: "GMT"

  DeployNetlify:
    runs-on: ubuntu-latest
    needs: [GetUniqueBuildId]
    environment:
      name: production
      url: https://acecentreorguk.netlify.app
    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      GITHUB_SHA: ${{ github.sha }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      IMAGE_URL: https://acecentreorguk.netlify.app
      BUILD_ID: ${{ needs.GetUniqueBuildId.outputs.buildId }}
      DEPLOY_KEY: production
      PROM_KEY: ${{ secrets.PROM_KEY }}
      MAILCHIMP_SERVER: ${{ secrets.MAILCHIMP_SERVER }}
      MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Patch deps
        run: yarn patch

      - name: Run netlify build
        run: netlify build --context production

      - name: Run netlify deploy
        run: netlify deploy --prod

      - name: Unpatch deps
        run: yarn reverse-patch
