name: Jest Tests
on: [pull_request]
jobs:
  JestTests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install NPM deps
        run: yarn install

      - name: Build Site
        run: yarn test
