name: Lighthouse CRON
on:
  workflow_dispatch:
  schedule:
    # Everyday at 5AM and 5PM
    - cron: "0 5,17 * * *"

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM deps
        run: yarn install

      - name: Run Lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: https://acecentreorguk.netlify.app
          LHCI_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
          UPLOAD_TO_LH: true
        run: yarn lighthouse --collect.numberOfRuns=5

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: lighthouse-results
          path: .lighthouseci
          # Github has size limits so this avoids hitting them
          retention-days: 1
