name: Pull Request Checks
on: [pull_request, workflow_dispatch]
jobs:
  DeployNetlifyDraft:
    runs-on: ubuntu-latest
    outputs:
      deploy-name: ${{ steps.get-title.outputs.result }}
      deploy-url: https://${{ steps.get-title.outputs.result }}--acecentreorguk.netlify.app
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - uses: actions/github-script@v4
        id: get-title

        with:
          result-encoding: string
          script: |
            const title = context.payload.pull_request.title;
            return title.toLowerCase().replace(/ /g,"-").slice(0,35);

      - name: Run netlify build
        run: netlify build --context deploy-preview --debug

      - name: Run netlify deploy
        run: netlify deploy --alias=${{ steps.get-title.outputs.result }}

  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run Jest Tests
        run: yarn test

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: jest-coverage
          path: coverage
          # Github has size limits so this avoids hitting them
          retention-days: 1

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run ESLint
        run: yarn run eslint .

  Cypress:
    needs: DeployNetlifyDraft
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node_modules-and-cypress-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run Cypress
        env:
          CYPRESS_BASE_URL: ${{ needs.DeployNetlifyDraft.outputs.deploy-url }}
        run: yarn cypress:run

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cypress-results
          path: artifacts
          # Github has size limits so this avoids hitting them
          retention-days: 1

  Lighthouse:
    needs: DeployNetlifyDraft
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run Lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: ${{ needs.DeployNetlifyDraft.outputs.deploy-url }}
          LHCI_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
        run: yarn lighthouse

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: lighthouse-results
          path: .lighthouseci
          # Github has size limits so this avoids hitting them
          retention-days: 1
