name: Pull Request Checks
on: [pull_request]
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM deps
        run: yarn install

      - name: Run Jest Tests
        run: yarn test

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: jest-coverage
          path: coverage
          # Github has size limits so this avoids hitting them
          retention-days: 1

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM deps
        run: yarn install

      - name: Run ESLint
        run: yarn run eslint .

  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM deps
        run: yarn install

      - name: Wait for netlify to deploy
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Pages changed - acecentreorguk
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Get netlify preview url
        uses: josephduffy/wait-for-netlify-action@v1
        id: wait-for-netlify-preview
        with:
          site_name: "acecentreorguk"
          max_timeout: 60

      - name: Run Cypress
        env:
          CYPRESS_BASE_URL: ${{ steps.wait-for-netlify-preview.outputs.url }}
        run: yarn cypress:run

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cypress-results
          path: artifacts
          # Github has size limits so this avoids hitting them
          retention-days: 1

  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM deps
        run: yarn install

      - name: Wait for netlify to deploy
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Pages changed - acecentreorguk
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Get netlify preview url
        uses: josephduffy/wait-for-netlify-action@v1
        id: wait-for-netlify-preview
        with:
          site_name: "acecentreorguk"
          max_timeout: 60

      - name: Run Lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: ${{ steps.wait-for-netlify-preview.outputs.url }}
          LHCI_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
        run: yarn lighthouse

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: lighthouse-results
          path: .lighthouseci
          # Github has size limits so this avoids hitting them
          retention-days: 1
