name: Pull Request Checks
on: [pull_request, workflow_dispatch]
jobs:
  CalculateDeployKey:
    runs-on: ubuntu-latest
    outputs:
      deploy-key: ${{ steps.get-title.outputs.result }}
    steps:
      - uses: actions/github-script@v4
        id: get-title
        with:
          result-encoding: string
          script: |
            const script = require('./scripts/calculate-deploy-key')
            return script(context);

  DeployNetlifyDraft:
    needs: CalculateDeployKey
    environment:
      name: ${{ needs.CalculateDeployKey.outputs.deploy-key }}
      url: https://${{ needs.CalculateDeployKey.outputs.deploy-key }}--acecentreorguk.netlify.app
    runs-on: ubuntu-latest
    outputs:
      deploy-name: ${{ needs.CalculateDeployKey.outputs.deploy-key }}
      deploy-url: https://${{ needs.CalculateDeployKey.outputs.deploy-key }}--acecentreorguk.netlify.app
    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      GITHUB_SHA: ${{ github.sha }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run netlify build
        run: netlify build --context deploy-preview --debug

      - name: Run netlify deploy
        run: netlify deploy --alias=${{ needs.CalculateDeployKey.outputs.deploy-key }}

  WarmUpCache:
    needs: DeployNetlifyDraft
    runs-on: ubuntu-latest
    steps:
      - name: Warm up resources
        run: curl ${{ needs.DeployNetlifyDraft.outputs.deploy-url }}/resources/all

  Jest:
    runs-on: ubuntu-latest
    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run Jest Tests
        run: yarn test

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: jest-coverage
          path: coverage
          # Github has size limits so this avoids hitting them
          retention-days: 1

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run ESLint
        run: yarn run eslint .

  Cypress:
    needs: [WarmUpCache, DeployNetlifyDraft]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM deps
        run: yarn install

      - name: Run Cypress
        env:
          CYPRESS_BASE_URL: ${{ needs.DeployNetlifyDraft.outputs.deploy-url }}
        run: yarn cypress:run

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cypress-results
          path: artifacts
          # Github has size limits so this avoids hitting them
          retention-days: 1

  Lighthouse:
    needs: [WarmUpCache, DeployNetlifyDraft]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - name: Run Lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: ${{ needs.DeployNetlifyDraft.outputs.deploy-url }}
          LHCI_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
        run: yarn lighthouse

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: lighthouse-results
          path: .lighthouseci
          # Github has size limits so this avoids hitting them
          retention-days: 1
