name: Send Slack Reminder
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 5"

jobs:
  SendSlackReminder:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install

      - uses: actions/github-script@v6
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_SECRET: ${{ secrets.SLACK_SECRET }}
        with:
          script: |
            const script = require('./scripts/send-reminder')
            return await script(context);
