name: Run Snapshot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  TriggerSnapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM deps
        run: yarn install
      - uses: actions/github-script@v8
        env:
          DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          script: |
            const script = require('./scripts/snapshot')
            return await script(context);
